-- 치의신보 뉴스 기사 저장 테이블
create table if not exists news_articles (
  id bigint generated by default as identity primary key,
  title text not null,
  link text unique not null,
  summary text,
  category text default 'latest', -- 'latest' (최신) 또는 'popular' (인기)
  published_at timestamptz default now(),
  created_at timestamptz default now()
);

-- 인덱스 생성
create index if not exists idx_news_articles_category on news_articles(category);
create index if not exists idx_news_articles_created_at on news_articles(created_at desc);

-- RLS 정책 설정
alter table news_articles enable row level security;

-- 읽기 권한: 모든 인증된 사용자
create policy "Allow authenticated users to read news"
  on news_articles for select
  to authenticated
  using (true);

-- 쓰기 권한: service_role만 (cron job에서 사용)
create policy "Allow service role to insert news"
  on news_articles for insert
  to service_role
  with check (true);

create policy "Allow service role to update news"
  on news_articles for update
  to service_role
  using (true);

create policy "Allow service role to delete news"
  on news_articles for delete
  to service_role
  using (true);

-- 오래된 기사 자동 정리를 위한 함수 (30일 이상 된 기사 삭제)
create or replace function cleanup_old_news_articles()
returns void as $$
begin
  delete from news_articles
  where created_at < now() - interval '30 days';
end;
$$ language plpgsql security definer;
