-- 해피콜 결과 테이블 생성
-- 이 스크립트를 Supabase Dashboard의 SQL Editor에서 실행하세요

CREATE TABLE IF NOT EXISTS public.happy_call_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date text NOT NULL,
    patient_name text NOT NULL,
    treatment text NOT NULL,
    notes text,
    CONSTRAINT happy_call_logs_pkey PRIMARY KEY (id)
);

-- RLS (Row Level Security) 활성화
ALTER TABLE public.happy_call_logs ENABLE ROW LEVEL SECURITY;

-- 모든 사용자가 읽기/쓰기 가능하도록 정책 설정 (기존 테이블과 동일)
CREATE POLICY "Enable all operations for everyone" ON public.happy_call_logs 
    FOR ALL 
    TO public 
    USING (true) 
    WITH CHECK (true);

-- 인덱스 생성 (날짜별 조회 최적화)
CREATE INDEX IF NOT EXISTS happy_call_logs_date_idx ON public.happy_call_logs(date);
CREATE INDEX IF NOT EXISTS happy_call_logs_patient_name_idx ON public.happy_call_logs(patient_name);

-- 테이블 설명
COMMENT ON TABLE public.happy_call_logs IS '환자 해피콜 결과 기록 테이블';
COMMENT ON COLUMN public.happy_call_logs.id IS '고유 식별자';
COMMENT ON COLUMN public.happy_call_logs.date IS '해피콜 날짜 (YYYY-MM-DD 형식)';
COMMENT ON COLUMN public.happy_call_logs.patient_name IS '환자명';
COMMENT ON COLUMN public.happy_call_logs.treatment IS '진료 내용';
COMMENT ON COLUMN public.happy_call_logs.notes IS '특이사항 (선택사항)';